### ISSUE TITLE
Decom CLA droplets

### ISSUE THREAD

**Issue by Krinkle** [jquery/infrastructure-puppet#12]
The https://cla.js.foundation site is configured in Cloudflare, and has the `jsf-cla-assistant` droplet (IP `159.203.165.250`, created 23 Oct 2016) as its backend.  This droplet appears not managed by either Puppet or Ansible, and I'm unable to SSH into this myself. @brianwarner Do you have access to this one?

Screenshot of https://cla.js.foundation  from before I powered off the droplet just now:
<img height="200" alt="Screenshot" src="https://user-images.githubusercontent.com/156867/207128742-801b3065-024d-49f3-8008-37b5382447c8.png">

We also have the former cla.jquery.net site, backed by the `cla-01.ops.jquery.net` droplet in DigitalOcean (IP `104.131.146.50`, created 5 Feb 2015), which I do have access to and is managed by Puppet. This uses the software at https://github.com/jquery/jquery-license, and was until recently also used dynamically by the https://contribute.jquery.org website through URLs like `http://contribute.jquery.org/CLA/status/?owner=jquery&repo=jquery&sha=XYZ`.

Next steps:

* [x] Determine whether the CLA data on `cla-01.ops.jquery.net` needs to be extracted and preserved somewhere. If yes, @Krinkle can help with this.
* [x] Determine who has access to the https://cla.js.foundation server.
* [x] Determine what's on the https://cla.js.foundation database.
* [x] If it needs to be extracted and preserved, do so.
* [x] Delete the `cla-01.ops.jquery.net` droplet, and remove CLA Puppet manifests.
* [x] Delete the `jsf-cla-assistant` droplet.
* [x] Set up redirect for cla.js.foundation, similar to what we do with contribute.jquery.org/CLA, docs.jquery.com view.jquery.com, etc already.

**Comment by jorydotcom** [comment]
Hi @Krinkle - to answer point 1, we do need to preserve the CLA data. We have exports for all of the projects as of March 2018, but we need to capture the data on contributions after March 2018 and through approximately Aug. 2021 (which is when this server stopped working and we switched everyone over to EasyCLA).  We do not need to save anything else about this infrastructure, IMO. We were previously able to log in to the CLA Assistant using the @JSFOwner GH account. As far as I know, everything was hosted on DO.

**Comment by timmywil** [comment]
I see you assigned me, which is fine. I found where all the data was saved and have put together a dump of the data. The current format is JSON files split up by project with each commit SHA with its associated email. Is the idea that this info be preserved in the form of some static page or is keeping the JSON files around in a git repo enough?

**Comment by timmywil** [comment]
As for jsf-cla-assistant, I'm also not sure who has access. I wonder if @dmethvin might know. Or, Dave might know who else we could ask.

**Comment by timmywil** [comment]
I've added Dave to the infrastructure-contrib team so he can see this.

**Comment by Krinkle** [comment]
@timmywil I've powered on the `jsf-cla-assistant` droplet, and gave it a new root password via the DigitalOcean recovery mode (password is in our 1Password Team). I've then added your ssh-rsa key to `/root/.ssh/authorized_keys`.

You should now be able to connect to it using `ssh -i ~/.ssh/your_key_file root@159.203.165.250`, then enter the root password when prompted.

**Comment by timmywil** [comment]
I was able to gather data dumps from jsf-cla-assistant as well. It seems it was using a mongo db and I have all the data in JSON files now. Again, I'm not sure what to do with these. We could preserve all of this in a (private?) repo.

**Comment by timmywil** [comment]
Just want to throw these links here. The old jsf-clia-assistant uses https://github.com/JSFoundation/cla-assistant, which is a fork of https://github.com/cla-assistant/cla-assistant

**Comment by timmywil** [comment]
@Krinkle What should I do with the data? I'm thinking a private repo that has folders for both jsf-cla-assistant and cla.jquery.net

**Comment by Krinkle** [comment]
@timmywil That sounds like a good thing to do yeah. I suspect OpenJSF's Legal team would also want it for their own records in some way. I recommend asking Jory/Ben/Robin for why/who needs this, since the request came from there originally.

**Comment by timmywil** [comment]
CLA archives are now available at https://github.com/jquery/cla-archive (private).

**Comment by Krinkle** [comment]
Two weeks ago, I:
* deleted the Tarsnap backups for `cla-01.ops.jquery.net`
* shutdown `cla-01.ops.jquery.net` and `jsf-cla-assistant` droplets at DigitalOcean.

I've now deleted both servers and their DNS entries, and set up a redirect from https://cla.js.foundation to https://cla.openjsf.org.
