### ISSUE TITLE
Upgrade from Debian 7 Wheezy (Puppet 3) to Debian 11 Bullseye (Puppet 7)

### ISSUE THREAD

**Issue by Krinkle** [jquery/infrastructure-puppet#8]
## List of hosts

https://github.com/jquery/infrastructure/blob/puppet-stage/manifests/site.pp

* [x] `puppet.ops.jquery.net`
* [x] `wp-01`, jquery.com
  * [x] jquery.com
  * [x] api.jquery.com
  * [x] learn.jquery.com
  * [x] plugins.jquery.com
* [x] `wp-02`, most other sites (incl *.jquery.org, jqueryui.com, etc)
* [x] `wp-03`, codeorigin.jquery.com, releases.jquery.com, and recipient of Git assets
* [x] `wp-01.stage`, WordPress doc sites, staging, all domains (stage.api.jquery.com, etc)
* [x] `builder-01`
* [x] `builder-03.stage`
* [x] `jq03.stage.jquery.com` (stage.demos.jquerymobile.com, stage.themeroller.jquerymobile.com)
* [x] ~`jenkins-01`~ decommissioned
* [x] `cla-01.ops.jquery.net`
* [x] `cla-01.stage.jquery.net`
* [x] `gruntjs.ops.jquery.net`
* [x] `gruntjs.stage.jquery.net`
* [x] `origin-01.ops.jquery.net`, contentorigin (content.jquery.com, static.jquery.com)
* [x] `swarm-01.ops.jquery.net`, TestSwarm
* [x] `view-01.ops.jquery.net`, View, git assets
* [x] `trac.ops.jquery.net`, Trac, (bugs.jquery.com, bugs.jquerui.com)

Dedicated tickets:

* [x] Reduce jQuery CDN risk, separate and upgrade codeorigin site. https://github.com/jquery/infrastructure/issues/554
* [x] Upgrade TestSwarm to PHP 7. https://github.com/jquery/infrastructure/issues/444
* [x] Upgrade WordPress hosts to PHP 7. https://github.com/jquery/infrastructure-puppet/issues/6
* [x] Trac: Replace with static export. https://github.com/jquery/infrastructure-puppet/issues/10
* [x] CLA export and decom. https://github.com/jquery/infrastructure-puppet/issues/12
* [x] Plugins: Replace with static export https://github.com/jquery/infrastructure-puppet/issues/29

## Overview

In order to get away from the very outdated Debian versions and such, we need to also get to a newer Puppet version.

We are currently using numerous Puppet 2 features that were deprecated in Puppet 3 and removed in Puppet 4. The main change that I think affects us is the change from "environment configs" to "environment directories".

Some relevant links:
* https://elatov.github.io/2016/07/upgrade-puppet-3x-to-4x/
* https://puppet.com/docs/puppet/4.10/upgrade_major_server.html
* https://puppet.com/docs/puppet/3.8/environments.html
* https://puppet.com/docs/puppet/3.8/dirs_manifest.html

## Status quo: Puppet 3

The puppet server runs at puppet.ops.jquery.net (in legacy docs: puppet-master). The config for the server is at `/etc/puppet/puppet.conf`. There are two Git clones that we care about on this server:

* `/etc/puppet` - This is a clone of jquery/infrastructure.git at branch `puppet-master`. This currently replaces the entire `/etc/puppet` directory.
* `/etc/puppet-stage` – This is a directory we made up, containing another clone of jquery/infrastructure.git at branch `puppet-stage`.

In `/etc/puppet/puppet.conf` (the only place the Puppet server actually looks at) we have the following stuff:

```
[main]
# …
templatedir=$confdir/templates
manifest=/etc/puppet/manifests/site.pp

[stage]
manifest=/etc/puppet-stage/manifests/site.pp
modulepath=/etc/puppet-stage/modules
# …

[master]
# …
```

By default, with one of our droplets that runs a puppet agent asks for provisioning, it gets provisoned by the main config which points simply at the subdirectories within `/etc/puppet`. On staging hosts, we have another `/etc/puppet/puppet.conf` file that may contain `environment = stage`, which the agent passes on to the Puppet server, and so the Puppet server will consider that manifest and modulepath directory instead (in addition to compling it with `$::environment = "stage"`).

Beyond this, the only other thing worth knowing is that we use `jquery::postreceive` instances (similar to for the content sites) to automatically update these git checkouts after commits to them. The actual applying of changes however is passive, based on puppet agents checking in with the server every 30 minutes (default Puppet agent behaviour).

## Puppet 4

Under Puppet 4, things are a little bit different. There is no longer support for the `templatedir`, `manifest`, and `modulepath` parameters, and there is no longer support for per-environment configuration section overrides.

Instead, modules are read from a directory like `/etc/puppet/code/environments/:environment/modules` and manifests are read from a directory like `/etc/puppet/code/environments/:environment/manifests`. For example: `/etc/puppet/code/environments/production/modules`.

I think global templates are no longer supported, or at least not varying by environment. But that's okay, we only have one file in `/templates` and that'll either just not support staging or maybe we can even get rid of it (do we still use Zabbix?).

The new directory layout seems feasible, we just create two more clones and keep both for a little while.

## Transition

I noticed just now that, apart from a few minor tweaks being needed for deprecated features, more generally it is not supported to connect Puppet 4 clients to a Puppet 3 server. However, the other way around is supported. So, the puppet master will have to go first, and that means a master switch, and setting up a new one of those first as well.

The good news is, a Puppet server is relatively easy to configure and gradually switch to...

**Comment by Krinkle** [comment]
I've set up a basic skeleton at <https://github.com/jquery/infrastructure-puppet> for the puppet server, and provisioned as follows:

```
ssh root@puppet-02.stage.ops.jquery.net
$ cd /etc/puppetlabs/environments
$ rm -rf production/

$ apt-get install git
$ git clone https://github.com/jquery/infrastructure-puppet.git production/
```

This does not require a deployment ssh key, it can be an unauthenticated clone over HTTPS since this is the public puppet repository.


@atdt I originally wanted to set it up such that the public repo reflects `/etc/puppetlabs/code` rather than `/etc/puppetlabs/code/environments/production/`, but I couldn't get use of the modules directory to work. I had the following on the puppet server at `/etc/puppetlabs/puppet/puppet.conf`

```
[main]
disable_per_environment_manifest = true
default_manifest = /etc/puppetlabs/code/manifests
basemodulepath = /etc/puppetlabs/code/modules
```

But alas, it wasn't applying anything. There was no error though, it ran cleanly on codeorigin-01, but just didn't apply any roles. So the modulepath may've worked but that it was `site.pp` that was being ignored. Alas, in https://github.com/jquery/infrastructure-puppet/commit/ec2631b5b97a0554e35f8d1ad6e7c6b55bb700d6 I moved it all down a level and that's working now.

```
root@codeorigin-01:~# puppet agent -tv
Info: Using environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Caching catalog for codeorigin-01.stage.ops.jquery.net
Info: Applying configuration version '(491cd5b) Timo Tijhof - get_config: Follows-up ec2631b5b9'
Notice: /Stage[main]/Role::Codeorigin/Package[nginx]/ensure: created
Notice: Applied catalog in 9.08 seconds
```

Let me know if anything is off here, or could be better. Otherwise, next steps:

* Settle on how to integrate private data.

I think it'd be neat if the public repo is standalone and self-sufficient for staging and local use, e.g. not hard-require a third repo with pseudo secrets to be integrated to substitute for the real secret repo. Instead, we might be able to get away with only having private data come from Hieradata YAML files, which have a straight-forward inheritence chain that we can configure in production to include one extra layer from a checkout of the private repo.

* Write a puppet role for the puppetserver itself:

In particular, the following non-trivial things seem best to provision via puppet instead of statically once:
* set up sysadmin user accounts and ssh keys.
* prune initial root keys (ref https://github.com/jquery/infrastructure/issues/560).
* provision a secret key that allows it to clone the private `infra-puppet-secret` repo. Also: this presents a bootstrapping problem, so we'll probably have to write a plain shell version as well that we document.  
* install node-notifier and provisioning it with a secret webhook to keep the checkout of `infra-puppet` and `infra-puppet-sectet` up-to-date.

**Comment by Krinkle** [comment]
I've provisioned myself and Ori on the new system, and also resolved https://github.com/jquery/infrastructure/issues/560 at the same time (Automatically remove unpuppetized root keys).

**Comment by Krinkle** [comment]
Last remaining work:

* Decom wp-01.ops.jquery.net (still serves `plugins.jquery.com`).
* Decom jenkins-01.ops.jquery.net.
* Decom puppet.ops.jquery.net (manages jenkins-01 and wp-01).

The first one is blocked on https://github.com/jquery/infrastructure-puppet/issues/29

**Comment by Krinkle** [comment]
I've deleted the tarsnap backups of wp-01 using the command at https://github.com/jquery/infrastructure-puppet/issues/19#issuecomment-1699644372, and turned off the droplet. I'll delete it next week if nothing comes up by then.

<img width="1064" alt="Screenshot 2024-04-24 at 20 14 38" src="https://github.com/jquery/infrastructure-puppet/assets/156867/d50e246a-4cbb-4c3c-8876-39efffe667ac">


Just shy of its 10 year anniversary. Pretty good uptime!

**Comment by timmywil** [comment]
Decommissioning jenkins can be tracked specifically here: https://github.com/jquery/infrastructure-puppet/issues/47

After that, we can decommission puppet.ops.jquery.net and close this issue.

**Comment by Krinkle** [comment]
Timmy deleted the jenkins-01 droplet. I've now also deleted its DNS definition, and done the same for `puppet.ops.jquery.net`, which ticks all the boxes on this task!

<img width="849" alt="puppet.ops.jquery.net. Debian 8.3. Created Feb 2016." src="https://github.com/jquery/infrastructure-puppet/assets/156867/10758491-e8a1-4764-98e1-be2c37f0e54b">
